### ISSUE TITLE
Address res.send(sqlResult) vs res.json(sqlResult) in controllers

### ISSUE THREAD

**Issue by dianastebbins** [dianastebbins/mark-it-react#51]
routes are inconsistent about what they return, res.send or res.json. It does matter back on the UI end if it needs to use that data, and I think it should be consistent. The UI should not have to look up what each different route returns, it should always be the same.

send function sets the content type to text/Html which means that the client will now treat it as text. It then returns the response to the client. The res. json function on the other handsets the content-type header to application/JSON so that the client treats the response string as a valid JSON object.Dec 2, 2019

Difference between res.send and res.json in Express.js

**Comment by zahraaliaghazadeh** [comment]
I wasnt sure if this is still needed to be open. I closed it but feel free to open if need to.
